models/User_project.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user_project".
 *
 * @property integer $id
 * @property integer $id_user
 * @property integer $id_project
 */
class User_project extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'id_project'], 'required'],
            [['id', 'id_user', 'id_project'], 'integer'],
			[['id_user', 'id_project'], 'unique', 'targetAttribute' => ['id_user', 'id_project'], 'message' => 'The user is already assigned to this project'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'User',
            'id_project' => 'Project',
        ];
    }
	
	public function getUserItem()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }	
	
	public function getProjectItem()
    {
        return $this->hasOne(Project::className(), ['id' => 'id_project']);
    }
	
			
}

controllers/ProjectController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Project;
use app\models\ProjectSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex($owner_projects = null)
    {
		
		if (\Yii::$app->user->can('can_admin')||\Yii::$app->user->can('can_ceo')){
			$owner_projects = null;
		}
		
		if (!\Yii::$app->user->can('can_preformTask')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        	
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $owner_projects);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		if (!\Yii::$app->user->can('can_preformTask')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        	
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = new Project();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
			if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UnauthorizedHttpException;

use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
		if (!\Yii::$app->user->can('can_admin')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
	//	if (!\Yii::$app->user->can('can_admin')&&!\Yii::$app->user->can('can_ceo'))
		//	throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserprojectController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User_project;
use app\models\User;
use app\models\User_projectSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\UnauthorizedHttpException;


/**
 * User_projectController implements the CRUD actions for User_project model.
 */
class UserprojectController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User_project models.
     * @return mixed
     */
    public function actionIndex($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        	
        $searchModel = new User_projectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$id);

		
		$allUsers = Yii::$app->db->createCommand('SELECT * FROM user 
			where `id` not in (
			select id_user 
			from user_project 
			where id_project = '.$id.')'

			);
			$allUsers = Yii::$app->db->createCommand('SELECT * FROM user') 
            ->queryAll();
			//$allUsers = User::find()->all();
		$allUsersArray = ArrayHelper::
					map($allUsers, 'id', 'name');
			
				
			
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'project'=>$id,
			'allUsersArray'=>$allUsersArray,
        ]);
    }

    /**
     * Displays a single User_project model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User_project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($project)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = new User_project(['id_project'=>$project]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id_project]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User_project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User_project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
		$myid = $this->findModel($id)->id_project;
        $this->findModel($id)->delete();

         return $this->redirect(['index', 'id' => $myid]);
    }

    /**
     * Finds the User_project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User_project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User_project::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/userproject/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\User;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model app\models\User_project */
/* @var $form yii\widgets\ActiveForm */
?>
<?php

$allUsers = Yii::$app->db->createCommand('SELECT * FROM user 
			where `id` not in (
			select id_user 
			from user_project 
			where id_project = '.$_GET['project'].')'

			)
		
            ->queryAll();
			
		$allUsersArray = ArrayHelper::
					map($allUsers, 'id', 'name');


?>
<div class="user-project-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php ///$form->field($model, 'id')->textInput() ?>

   
	 <?= $form->field($model,  'id_user')->dropDownList($allUsersArray) ?>

    <?php //$form->field($model, 'id_project')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Add' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		
		<?= Html::a('Cancel', ['/userproject/index','id'=>$_GET['project']], ['class' => 'btn btn-warning']) ?>
      
	</div>

    <?php ActiveForm::end(); ?>

</div>

views/userproject/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User_projectSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-project-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'id_project') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/userproject/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User_project */

$this->title = 'Add Project Member';
$this->params['breadcrumbs'][] = ['label' => 'User Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-project-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
		'project'=>$project,
    ]) ?>

</div>

views/userproject/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\models\Project;
/* @var $this yii\web\View */
/* @var $searchModel app\models\User_projectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$task = Project::find()->where(['id'=>$_GET['id']])->all();
$this->title = $task[0]->name;

//$this->title = 'Project Members';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-project-index">
	
    <h1><?= Html::encode($this->title) ?></h1><h3>Project Members</h3>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
	<?php if (\Yii::$app->user->can('can_projectManager')){ ?>
        <?= Html::a('Add Project Member', ['create','project'=>$project], ['class' => 'btn btn-success']) ?>
	<?php } ?>
		<?= Html::a('Back to project page', ['project/view','id'=>$_GET['id']], ['class' => 'btn btn']) ?>
   
	</p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
          //  ['class' => 'yii\grid\SerialColumn'],

          //  'id',
           // 'id_user',
			 [
				'attribute' => 'id_user',
				'label' => 'Member',
				'format' => 'raw',
				'value' => function($model){
							//return ($model->ownerItem->name);
							 return Html::a($model->userItem->name, ['user/view', 'id' => $model->userItem->id]);
					},		
				/* 'value' => function($model){
							 return Html:: a($model->authorItem->name);
					},		 */
			],
           // 'id_project',
			['class' => ActionColumn::className(),'template'=>'{delete} ' ]
          //  ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/userproject/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User_project */

$this->title = 'Update User Project: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-project-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/userproject/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User_project */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-project-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_user',
            'id_project',
        ],
    ]) ?>

</div>