models/User_task.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user_task".
 *
 * @property integer $id
 * @property integer $id_task
 * @property integer $id_user
 */
class User_task extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_task';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_task', 'id_user'], 'required'],
            [['id_task', 'id_user'], 'integer'],
			[['id_user', 'id_task'], 'unique', 'targetAttribute' => ['id_user', 'id_task'], 'message' => 'The user is already assigned to this task'],
        
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_task' => 'task',
            'id_user' => 'user',
        ];
    }
	
	public function getUserItem()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }	
	
	public function getTaskItem()
    {
        return $this->hasOne(Task::className(), ['id' => 'id_task']);
    }
	
}

controllers/TaskController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Task;
use app\models\TaskSearch;
use yii\web\Controller;
use app\models\Status;
use app\models\Priority;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex($team_tasks = null,$own_tasks = null)
    {
		if (\Yii::$app->user->can('can_preformTask')&&!\Yii::$app->user->can('can_admin')&&!\Yii::$app->user->can('can_ProjectManager')){
			$own_tasks = Yii::$app->user->getId();
		}
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $team_tasks, $own_tasks);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
				'statuses' => Status::getStatusesWithAllStatuses(),
				'status' => $searchModel->status,
				'priorities' => Priority::getPrioritiesWithAllPriorities(),
				'priority' => $searchModel->priority,				
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
			
	if (!\Yii::$app->user->can('can_ProjectManager'))
		throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		if (!\Yii::$app->user->can('can_preformTask'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to delete tasks');
        
		
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UnauthorizedHttpException;

use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
		if (!\Yii::$app->user->can('can_admin')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
	//	if (!\Yii::$app->user->can('can_admin')&&!\Yii::$app->user->can('can_ceo'))
		//	throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		if (!\Yii::$app->user->can('can_admin'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UsertaskController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User_task;
use app\models\User_taskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * User_taskController implements the CRUD actions for User_task model.
 */
class UsertaskController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User_task models.
     * @return mixed
     */
    public function actionIndex($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $searchModel = new User_taskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$id);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'task'=>$id,
        ]);
    }

    /**
     * Displays a single User_task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager')&&!\Yii::$app->user->can('can_ceo'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User_task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($task)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = new User_task(['id_task'=>$task]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id_task]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User_task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User_task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		if (!\Yii::$app->user->can('can_ProjectManager'))
			throw new UnauthorizedHttpException ('You are not allowed to access this page');
        
		
		$myid = $this->findModel($id)->id_task;
		
        $this->findModel($id)->delete();

         return $this->redirect(['index', 'id' => $myid]);
    }

    /**
     * Finds the User_task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User_task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User_task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/usertask/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Task;
use app\models\User;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\User_task */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
//$tasks = Task::find()->where(['id'=>$_GET['task']])->all();
$task = Task::find()->where(['id'=>$_GET['task']])->one();
//$task = $tasks[0];
//echo $task->projectItem->id;
 $allUsers = Yii::$app->db->createCommand('SELECT * FROM user 
			where `id`  in (
			SELECT `id_user`  
			FROM `user_project`
			WHERE `id_project` = '.$task->projectItem->id.')
			and `id`  not in (
			select id_user 
			from user_task 
			where id_task = '.$_GET['task'].')'

			
			
			)
			
		
            ->queryAll(); 
			
		$allUsersArray = ArrayHelper::
					map($allUsers, 'id', 'name');


?>
<div class="user-task-form">

    <?php $form = ActiveForm::begin(); ?>

 
   <?= $form->field($model,  'id_user')->dropDownList($allUsersArray) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Add' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		
		<?= Html::a('Cancel', ['/usertask/index','id'=>$_GET['task']], ['class' => 'btn btn-warning']) ?>
         </div>

    <?php ActiveForm::end(); ?>

</div>

views/usertask/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User_taskSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-task-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_task') ?>

    <?= $form->field($model, 'id_user') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/usertask/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User_task */

$this->title = 'Assign user to task';
$this->params['breadcrumbs'][] = ['label' => 'User Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-task-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/usertask/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\models\Task;
/* @var $this yii\web\View */
/* @var $searchModel app\models\User_taskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$task = Task::find()->where(['id'=>$_GET['id']])->all();
$this->title = $task[0]->title;
//$this->title = 'Task Members';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-task-index">

    <h1><?= Html::encode($this->title) ?></h1><h3>Task Members</h3>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
	<?php if (\Yii::$app->user->can('can_projectManager')){ ?>
        <?= Html::a('Add Task Members', ['create','task'=>$_GET['id']], ['class' => 'btn btn-success']) ?>
			<?php } ?>
		<?= Html::a('Back to task page', ['task/view','id'=>$_GET['id']], ['class' => 'btn btn']) ?>
   
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
           // ['class' => 'yii\grid\SerialColumn'],

          //  'id',
            [
				'attribute' => 'id_user',
				'label' => 'Member',
				'format' => 'raw',
				'value' => function($model){
							//return ($model->ownerItem->name);
							 return Html::a($model->userItem->name, ['user/view', 'id' => $model->userItem->id]);
					},		
				/* 'value' => function($model){
							 return Html:: a($model->authorItem->name);
					},		 */
			],
           // 'id_project',
			['class' => ActionColumn::className(),'template'=>'{delete} ' ]
          //  ['class' => 'yii\grid\ActionColumn'],
        ],
        
    ]); ?>
</div>

views/usertask/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User_task */

$this->title = 'Update User Task: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-task-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/usertask/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User_task */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-task-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_task',
            'id_user',
        ],
    ]) ?>

</div>